### ISSUE TITLE
Failed to activate the redux-devtools package

### ISSUE THREAD

**Issue by duketwo** [zalmoxisus/atom-redux-devtools#2]
**Atom Version**: 1.6.1
**System**: Mac OS X 10.11.3
**Thrown From**: [redux-devtools](https://github.com/zalmoxisus/atom-redux-devtools) package, v0.1.1
### Stack Trace

Failed to activate the redux-devtools package

```
At Cannot find module 'react-desktop/lib/Window/Window.osx'

Error: Cannot find module 'react-desktop/lib/Window/Window.osx'
  at Module._resolveFilename (module.js:336:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/bader/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/components/Settings.js:17:15)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/bader/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/components/ButtonBar.js:27:17)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/bader/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/index.js:36:18)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/bader/.atom/packages/redux-devtools/lib/index.js:19:21)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:172:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:800:25
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
 15x -5:09.3.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -0:14.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  9x -0:12.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.9.0 devtools:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "keyboard-localization"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
nuclide, v0.127.0
redux-devtools, v0.1.1

# Dev
No dev packages
```

**Comment by zalmoxisus** [comment]
Thanks for the report. I fixed it in `remotedev-app` please try again to install it

**Comment by duketwo** [comment]
Thanks, works now.
