### ISSUE TITLE
Getting uncaught error

### ISSUE THREAD

**Issue by nuhbye** [zalmoxisus/atom-redux-devtools#4]
[Enter steps to reproduce below:]
1. Whenever the number of entries in the list of events go beyond 2 pages it throws error.

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [redux-devtools](https://github.com/zalmoxisus/atom-redux-devtools) package, v0.3.2
### Stack Trace

Uncaught TypeError: Cannot read property 'timestamp' of undefined

```
At /Users/nuhbye/.atom/packages/redux-devtools/node_modules/redux-devtools-inspector/lib/ActionList.js:58

TypeError: Cannot read property 'timestamp' of undefined
  at getTimestamps (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/redux-devtools-inspector/lib/ActionList.js:58:31)
  at /Users/nuhbye/.atom/packages/redux-devtools/node_modules/redux-devtools-inspector/lib/ActionList.js:138:27
  at Array.map (native)
  at ActionList.render (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/redux-devtools-inspector/lib/ActionList.js:130:29)
  at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:796:32)
  at ReactCompositeComponentMixin._renderValidatedComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:819:34)
  at ReactCompositeComponentMixin._updateRenderedComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:743:36)
  at ReactCompositeComponentMixin._performComponentUpdate (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:721:10)
  at ReactCompositeComponentMixin.updateComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:642:12)
  at ReactCompositeComponentMixin.receiveComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at Object.ReactReconciler.receiveComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactReconciler.js:126:22)
  at Object.ReactChildReconciler.updateChildren (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactChildReconciler.js:110:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactMultiChild.js:215:28)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactMultiChild.js:314:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactMultiChild.js:301:12)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactDOMComponent.js:942:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactDOMComponent.js:760:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactDOMComponent.js:718:10)
  at Object.ReactReconciler.receiveComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactReconciler.js:126:22)
  at ReactCompositeComponentMixin._updateRenderedComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:751:23)
  at ReactCompositeComponentMixin._performComponentUpdate (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:721:10)
  at ReactCompositeComponentMixin.updateComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:642:12)
  at ReactCompositeComponentMixin.receiveComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at Object.ReactReconciler.receiveComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactReconciler.js:126:22)
  at ReactCompositeComponentMixin._updateRenderedComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:751:23)
  at ReactCompositeComponentMixin._performComponentUpdate (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:721:10)
  at ReactCompositeComponentMixin.updateComponent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:642:12)
  at ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactCompositeComponent.js:558:12)
  at Object.ReactReconciler.performUpdateIfNecessary (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactReconciler.js:158:22)
  at runBatchedUpdates (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactUpdates.js:151:21)
  at ReactReconcileTransaction.Mixin.perform (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/Transaction.js:138:20)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/Transaction.js:138:20)
  at ReactUpdatesFlushTransaction._assign.perform (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactUpdates.js:90:38)
  at Object.flushBatchedUpdates (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactUpdates.js:173:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/Transaction.js:204:25)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/Transaction.js:151:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.enqueueUpdate (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactUpdates.js:201:22)
  at enqueueUpdate (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactUpdateQueue.js:25:16)
  at Object.ReactUpdateQueue.enqueueSetState (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactUpdateQueue.js:210:5)
  at Connect.ReactComponent.setState (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react/lib/ReactComponent.js:64:16)
  at Connect.handleChange (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/react-redux/lib/components/connect.js:301:14)
  at /Users/nuhbye/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/store/createDevStore.js:47:14
  at Array.forEach (native)
  at update (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/store/createDevStore.js:46:15)
  at Object.setState (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/store/createDevStore.js:55:5)
  at updateState (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/store/updateState.js:79:21)
  at /Users/nuhbye/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/store/createRemoteStore.js:50:31
  at Emitter.watch (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/services/messaging.js:82:5)
  at Emitter.emit (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/component-emitter/index.js:131:20)
  at Emitter.SCEmitter.emit (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/sc-emitter/index.js:28:26)
  at Emitter.SCSocket._privateEventHandlerMap.#publish (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/socketcluster-client/lib/scsocket.js:170:28)
  at Emitter.SCSocket._onSCEvent (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/socketcluster-client/lib/scsocket.js:604:13)
  at Emitter.<anonymous> (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/socketcluster-client/lib/scsocket.js:289:12)
  at Emitter.emit (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/component-emitter/index.js:131:20)
  at Emitter.SCEmitter.emit (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/sc-emitter/index.js:28:26)
  at Emitter.SCTransport._onMessage (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/socketcluster-client/lib/sctransport.js:174:32)
  at WebSocket.wsSocket.onmessage (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/socketcluster-client/lib/sctransport.js:73:10)
  at WebSocket.onMessage (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/ws/lib/WebSocket.js:442:14)
  at emitTwo (events.js:100:13)
  at WebSocket.emit (events.js:185:7)
  at Receiver.ontext (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/ws/lib/WebSocket.js:841:10)
  at /Users/nuhbye/.atom/packages/redux-devtools/node_modules/ws/lib/Receiver.js:536:18
  at Receiver.applyExtensions (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/ws/lib/Receiver.js:371:5)
  at /Users/nuhbye/.atom/packages/redux-devtools/node_modules/ws/lib/Receiver.js:508:14
  at Receiver.flush (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/ws/lib/Receiver.js:347:3)
  at Receiver.opcodes.1.finish (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/ws/lib/Receiver.js:541:12)
  at Receiver.expectHandler (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/ws/lib/Receiver.js:499:31)
  at Receiver.add (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/ws/lib/Receiver.js:103:24)
  at Socket.realHandler (/Users/nuhbye/.atom/packages/redux-devtools/node_modules/ws/lib/WebSocket.js:825:20)
  at emitOne (events.js:90:13)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at TCP.onread (net.js:531:20)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "language-babel",
      "formatter"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.15.0 (active)
formatter, v2.12.3 (inactive)
git-plus, v5.18.0 (active)
highlight-selected, v0.11.2 (active)
javascript-snippets, v1.2.1 (active)
language-babel, v2.42.3 (inactive)
nuclide, v0.171.0 (active)
pigments, v0.35.3 (active)
react, v0.16.0 (active)
redux-devtools, v0.3.2 (active)
redux-snippets, v0.2.2 (active)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by zalmoxisus** [comment]
It seems that there's an old version of `remotedev-app`.

Did you installed this package recently? If not please remove it and install again so it will get the latest version of `remotedev-app`.

**Comment by nuhbye** [comment]
After updating, I am not facing this issue.

Thanks

**Comment by kevinrenskers** [comment]
I'm having the exact same issue, not sure what I should update? All my NPM and Atom packages are up to date.

**Comment by zalmoxisus** [comment]
@kevinrenskers, I've just published a new package (0.3.3), please update it and let me know if it fixes the issue.

**Comment by kevinrenskers** [comment]
Yep haven't had the error so far. Thanks!

**Comment by kevinrenskers** [comment]
Damn, just got it again.

```
Uncaught TypeError: Cannot read property 'timestamp' of undefined
/Users/kevin/.atom/packages/redux-devtools/node_modules/redux-devtools-inspector/lib/ActionList.js:58
```

**Comment by zalmoxisus** [comment]
@kevinrenskers, try to update [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools) as well. Could you share a reproducible example?

**Comment by kevinrenskers** [comment]
I'm already on the latest version (0.5.0). No real example, just when action 31 is fired off it starts to happen. The first 30 actions are fine.

**Comment by kevinrenskers** [comment]
It doesn't matter what the action or payload is either. It's always the 31st that starts to give the error.

**Comment by zalmoxisus** [comment]
Cannot reproduce. Most likely it was related to #5 as the package wasn't updated properly. Let me know if updating the package again helped.

**Comment by kevinrenskers** [comment]
I was still getting that CSS error after upgrading so I'm sorry to say that I uninstalled the package and am now using the React Native Debugger app instead.

**Comment by zalmoxisus** [comment]
@kevinrenskers, React Native Debugger also is using `remotedev-app` under the hood, the difference is that it uses an older version for now. So, if you could provide a reproductible example to solve that, it would help for that as well.
