### ISSUE TITLE
Uncaught Error: Cannot find module 'react/lib/EventPluginHub'

### ISSUE THREAD

**Issue by vtsatskin** [zalmoxisus/atom-redux-devtools#6]
1. Install atom-redux-devtools
2. Restart atom

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12.1
**Thrown From**: [redux-devtools](https://github.com/zalmoxisus/atom-redux-devtools) package, v0.5.0

### Stack Trace

Uncaught Error: Cannot find module 'react/lib/EventPluginHub'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:364

Error: Cannot find module 'react/lib/EventPluginHub'
    at Module._resolveFilename (module.js:440:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at injectTapEventPlugin (/Users/vt/.atom/packages/redux-devtools/node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js:23:3)
    at Object.<anonymous> (/Users/vt/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/hoc.js:41:35)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/vt/.atom/packages/redux-devtools/node_modules/remotedev-app/lib/index.js:15:12)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/vt/.atom/packages/redux-devtools/lib/index.js:5:33)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "terminal-plus",
      "activate-power-mode",
      "git-time-machine",
      "tree-view"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".hg",
      "obj-"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "firewatch-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-csscomb, v2.0.4 (inactive)
color-picker, v2.2.2 (inactive)
devdocs, v0.2.1 (inactive)
firewatch-syntax, v1.0.1 (active)
git-plus, v5.23.3 (inactive)
git-time-machine, v1.5.3 (inactive)
language-diff, v0.6.0 (inactive)
language-latex, v1.0.0 (inactive)
language-rspec, v0.5.0 (inactive)
language-rust, v0.4.8 (inactive)
language-scala, v1.1.8 (inactive)
linter, v1.11.18 (inactive)
linter-eslint, v8.0.0 (inactive)
linter-tidy, v2.2.1 (inactive)
markdown-lists, v0.0.2 (inactive)
merge-conflicts, v1.4.4 (inactive)
native-ui, v0.19.1 (inactive)
normalized-light-syntax, v0.8.1 (inactive)
nuclide, v0.183.0 (inactive)
pigments, v0.37.0 (inactive)
pretty-json, v1.6.1 (inactive)
redux-devtools, v0.5.0 (inactive)
relative-numbers, v0.5.1 (inactive)
seti-ui, v1.3.2 (inactive)
sort-lines, v0.14.0 (inactive)
tablr, v1.5.5 (inactive)
terminal-plus, v0.14.5 (inactive)
tidy-tabs, v0.3.0 (inactive)
vim-mode, v0.65.1 (inactive)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.46.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by zalmoxisus** [comment]
The incompatibility with React@15.4 was fixed in https://github.com/zalmoxisus/remotedev-app/pull/26, but it's not released yet. Let's stick to React@15.3 for now.

Just published a patch. Please update the package.

**Comment by vtsatskin** [comment]
Thanks for the blazing quick fix!
